%%%plot MID concentration and fluxes for a give soln%%%
%%%additionally plot data and show residues if soln generated by optimisation%%%

OFspec = OpenFLUX.OFobjSpecification(mfilename,OFspecFileName);

load(strcat(OFspec.loadFolder,OFspec.fileName));

if OF.isOptimisation%%%plot optimisation results
    if isempty(opSave.xFeas) && opSave.solnIndex == 0
        disp('at least a feasible soln is required')
        return
    elseif opSave.solnIndex==0
        solnToVisualise = opSave.xFeas;
    else
        solnToVisualise = opSave.xFitSeries(opSave.solnIndex).xFinish;
    end
    [simEMU,simConc,simFlux,simTime,mid_outParsed] = OF.generatePlotData(solnToVisualise);
    
    if OFspec.simResidualError
        if opSave.isODE
            [f, Yj,fConc_diff,fMID_diff,rad_diff] = opSave.fitFxn(solnToVisualise);
        else
            [f, metConcProfile,EMUstateStore,vProfile,fConc_diff,fMID_diff,rad_diff,vInt] = opSave.fitFxn(solnToVisualise);
        end
        metSeq = [1:OF.opInput.noExpData]'*ones(1,numel(OF.sampleTime));
        tablePrint = OF.dataMet(:,1);
        for j = 1:size(tablePrint,1)
            tablePrint{j,2} = fConc_diff(metSeq==j)'*fConc_diff(metSeq==j);
            tablePrint{j,3} = fMID_diff(OF.dataMet{j,9}(:,2))'*fMID_diff(OF.dataMet{j,9}(:,2));
        end
        resTab = cell2mat(tablePrint(:,2:3));
        [~,index] = sort(sum(resTab,2),'descend');
        tablePrint = tablePrint(index,:);
        totalRes = sum(sum(resTab)); 
        for i = 1:size(tablePrint,1)
            tablePrint{i,2} = num2str(round(tablePrint{i,2}/totalRes,3));
            tablePrint{i,3} = num2str(round(tablePrint{i,3}/totalRes,3));
        end
        tablePrint = [{'metName' '%concRes' '%isotopRes'};tablePrint];
        tablePrint = pad(tablePrint);
        fprintf('total res: %1.0f\n',totalRes);
        fprintf('\n');
        disp(['rank metabolites'' residual error']);
        for i = 1:size(tablePrint,1)
            fprintf('%s\t%s\t%s\n',tablePrint{i,:})
        end
    end
    
    
else%%%plot simulation results, no met data, no isotope correction
    [simEMU,simConc,simFlux,simTime,mid_outParsed] = OF.generatePlotData(simSave.xFeas);
end

drawFig1(1,[],mid_outParsed,simTime,OF.sampleTime);
