%%%plot MID concentration and fluxes for a give soln%%%
%%%additionally plot data and show residues if soln generated by optimisation%%%

OFspec = OpenFLUX.OFobjSpecification(mfilename,OFspecFileName);

load(strcat(OFspec.loadFolder,OFspec.fileName));

if OFspec.loadOP%%%plot optimisation results
    if isempty(opSave.xFeas) && opSave.solnIndex == 0
        disp('at least a feasible soln is required')
        return
    elseif opSave.solnIndex==0
        solnToVisualise = opSave.xFeas;
    else
        solnToVisualise = opSave.xFitSeries(opSave.solnIndex).xFinish;
    end
    [simEMU,simConc,simFlux,simTime,mid_outParsed] = OF.generatePlotData(solnToVisualise);
    
    if OFspec.simResidualError
        if opSave.isODE
            [f, Yj,fConc_diff,fMID_diff,rad_diff,Ycopy3] = opSave.fitFxn(solnToVisualise);
        else
            [f, metConcProfile,EMUstateStore,vProfile,fConc_diff,fMID_diff,rad_diff,vInt] = opSave.fitFxn(solnToVisualise);
        end
    end
    
    
else%%%plot simulation results, no met data, no isotope correction
    [simEMU,simConc,simFlux,simTime,mid_outParsed] = OF.generatePlotData(simSave.xFeas);
end

drawFig1(1,[],mid_outParsed,simTime,OF.sampleTime);
